# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.16.1

# Mod Properties
mod_version=1.0.0
maven_group=cc.prism
archives_base_name=prism

# Dependencies
fabric_version=0.154.2+26.1.2

# Java version
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.4.101-hotspot
org.gradle.java.installations.auto-detect=false
